import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { resolveProfilePaths } from "../../packages/config/dist/index.js";
import { openOpenRillStateDatabase } from "../../packages/state/dist/index.js";
import { ConversationError, ConversationService } from "../../packages/conversations/dist/index.js";
import { readHostMetadata, startLocalHost } from "../../services/agent-host/dist/index.js";

function ids(prefix="id") { let n=0; return ()=>`${prefix}-${++n}`; }
async function fixture(workspaceIds=["alpha"]) {
  const root=await mkdtemp(join(tmpdir(),"openrill-step006-"));
  const env={OPENRILL_DATA_ROOT:join(root,"data"),OPENRILL_CONFIG_ROOT:join(root,"config")};
  const paths=resolveProfilePaths({profile:"ledger",env});
  const state=await openOpenRillStateDatabase({profilePaths:paths});
  let now=1000;
  const service=new ConversationService({state,workspaceIds,now:()=>++now,createId:ids()});
  return {root,env,paths,state,service,cleanup:async()=>{if(state.isOpen())state.close();await rm(root,{recursive:true,force:true});}};
}

test("conversation create, list, and get are workspace scoped",async()=>{const f=await fixture(["alpha","beta"]);try{const a=f.service.create({workspaceId:"alpha",title:"A"});f.service.create({workspaceId:"beta",title:"B"});assert.equal(f.service.list({workspaceId:"alpha"}).length,1);assert.equal(f.service.get({workspaceId:"alpha",conversationId:a.conversationId}).title,"A");assert.throws(()=>f.service.get({workspaceId:"beta",conversationId:a.conversationId}),e=>e instanceof ConversationError&&e.code==="WORKSPACE_ACCESS_DENIED");}finally{await f.cleanup();}});

test("messages allocate strict per-conversation ordering",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const one=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s1",text:"one"});const two=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s2",text:"two"});assert.deepEqual([one.message.sequence,two.message.sequence],[1,2]);assert.deepEqual(f.service.get({workspaceId:"alpha",conversationId:c.conversationId}).messages.map(m=>m.sequence),[1,2]);}finally{await f.cleanup();}});

test("submission idempotency replays identical input and rejects conflicting input",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const one=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"same",text:"hello"});const replay=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"same",text:"hello"});assert.equal(replay.replayed,true);assert.equal(replay.run.runId,one.run.runId);assert.throws(()=>f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"same",text:"changed"}),e=>e instanceof ConversationError&&e.code==="SUBMISSION_CONFLICT");}finally{await f.cleanup();}});

test("run events are append-only, sequence checked, and idempotent",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const sent=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s",text:"x"});const e=f.service.appendEvent({runId:sent.run.runId,eventType:"run.checkpoint",payload:{step:1},idempotencyKey:"checkpoint",expectedSequence:2});assert.equal(e.sequence,2);assert.equal(f.service.appendEvent({runId:sent.run.runId,eventType:"run.checkpoint",payload:{step:1},idempotencyKey:"checkpoint",expectedSequence:99}).replayed,true);assert.throws(()=>f.service.appendEvent({runId:sent.run.runId,eventType:"run.note",payload:{},expectedSequence:9}),x=>x instanceof ConversationError&&x.code==="EVENT_SEQUENCE_CONFLICT");assert.throws(()=>f.service.appendEvent({runId:sent.run.runId,eventType:"run.checkpoint",payload:{step:2},idempotencyKey:"checkpoint"}),x=>x instanceof ConversationError&&x.code==="EVENT_IDEMPOTENCY_CONFLICT");assert.deepEqual(f.service.events(sent.run.runId).map(x=>x.sequence),[1,2]);}finally{await f.cleanup();}});

test("run state machine permits only declared transitions",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const s=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s",text:"x"});assert.equal(f.service.transitionRun({runId:s.run.runId,status:"RUNNING"}).status,"RUNNING");assert.equal(f.service.transitionRun({runId:s.run.runId,status:"WAITING_APPROVAL"}).status,"WAITING_APPROVAL");assert.equal(f.service.transitionRun({runId:s.run.runId,status:"COMPLETED"}).status,"COMPLETED");assert.throws(()=>f.service.transitionRun({runId:s.run.runId,status:"RUNNING"}),e=>e instanceof ConversationError&&e.code==="RUN_STATE_INVALID");}finally{await f.cleanup();}});

test("conversation projection is rebuildable from authoritative ledger",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s1",text:"one"});f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s2",text:"two"});f.state.transaction(r=>r.conversations.deleteProjection(c.conversationId));const rebuilt=f.service.rebuildProjection(c.conversationId);assert.equal(rebuilt.messageCount,2);assert.equal(rebuilt.lastMessageSequence,2);assert.ok(rebuilt.lastRunId);}finally{await f.cleanup();}});

test("restart recovery marks checkpointed running run resumable",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const s=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s",text:"x"});const running=f.service.transitionRun({runId:s.run.runId,status:"RUNNING"});f.service.appendEvent({runId:s.run.runId,eventType:"run.checkpoint",payload:{safe:true}});const out=f.service.recoverIncompleteRuns();assert.deepEqual(out.map(x=>[x.status,x.recoveryState]),[["CREATED","RESUMABLE"]]);const recovered=f.state.transaction(r=>r.conversations.getRun(s.run.runId));assert.equal(recovered.currentAttemptId,running.currentAttemptId);const interrupted=f.state.transaction(r=>r.conversations.getAttempt(running.currentAttemptId));assert.equal(interrupted.status,"ABORTED");assert.equal(interrupted.recoveryReason,"HOST_RESTART");const resumed=f.service.transitionRun({runId:s.run.runId,status:"RUNNING"});assert.notEqual(resumed.currentAttemptId,running.currentAttemptId);const next=f.state.transaction(r=>r.conversations.getAttempt(resumed.currentAttemptId));assert.equal(next.attemptNumber,2);}finally{await f.cleanup();}});

test("restart recovery remains resumable while the post-checkpoint model request is in flight",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const s=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s",text:"x"});const running=f.service.transitionRun({runId:s.run.runId,status:"RUNNING"});f.service.appendEvent({runId:s.run.runId,attemptId:running.currentAttemptId,eventType:"run.checkpoint",payload:{kind:"tool.completed",toolCallId:"browser-open"}});const invocation=f.service.startModelInvocation({runId:s.run.runId,attemptId:running.currentAttemptId,turnNumber:2,requestNumber:2,providerId:"fixture",modelId:"fixture",requestHash:"a".repeat(64)});f.service.appendEvent({runId:s.run.runId,attemptId:running.currentAttemptId,eventType:"model.requested",payload:{turn:2,requestNumber:2}});const [out]=f.service.recoverIncompleteRuns();assert.deepEqual([out.status,out.recoveryState],["CREATED","RESUMABLE"]);const recoveredInvocation=f.service.modelInvocations(s.run.runId).find(item=>item.invocationId===invocation.invocationId);assert.equal(recoveredInvocation.status,"FAILED");assert.equal(recoveredInvocation.errorCode,"MODEL_INTERRUPTED_BY_RESTART");assert.ok(recoveredInvocation.endedAt);}finally{await f.cleanup();}});

test("restart recovery marks uncheckpointed running run non-resumable",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const s=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s",text:"x"});f.service.transitionRun({runId:s.run.runId,status:"RUNNING"});const out=f.service.recoverIncompleteRuns();assert.deepEqual(out.map(x=>[x.status,x.recoveryState]),[["FAILED","NON_RESUMABLE"]]);}finally{await f.cleanup();}});

test("waiting approval remains resumable across restart classification",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const s=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s",text:"x"});f.service.transitionRun({runId:s.run.runId,status:"RUNNING"});f.service.transitionRun({runId:s.run.runId,status:"WAITING_APPROVAL"});const [out]=f.service.recoverIncompleteRuns();assert.equal(out.status,"WAITING_APPROVAL");assert.equal(out.recoveryState,"RESUMABLE");}finally{await f.cleanup();}});

test("cancel is effective for active run and idempotent for terminal run",async()=>{const f=await fixture();try{const c=f.service.create({workspaceId:"alpha"});const s=f.service.send({workspaceId:"alpha",conversationId:c.conversationId,submissionKey:"s",text:"x"});f.service.transitionRun({runId:s.run.runId,status:"RUNNING"});const first=f.service.cancel({workspaceId:"alpha",conversationId:c.conversationId,runId:s.run.runId});const second=f.service.cancel({workspaceId:"alpha",conversationId:c.conversationId,runId:s.run.runId});assert.equal(first.run.status,"CANCELLED");assert.equal(first.alreadyTerminal,false);assert.equal(second.alreadyTerminal,true);}finally{await f.cleanup();}});

test("foreign and unknown workspaces fail closed",async()=>{const f=await fixture(["alpha"]);try{assert.throws(()=>f.service.create({workspaceId:"foreign"}),e=>e instanceof ConversationError&&e.code==="WORKSPACE_ACCESS_DENIED");}finally{await f.cleanup();}});

function collector(socket){const q=[];const waits=[];socket.addEventListener("message",e=>{const f=JSON.parse(String(e.data));const i=waits.findIndex(w=>w.p(f));if(i>=0){const [w]=waits.splice(i,1);clearTimeout(w.t);w.r(f);}else q.push(f);});return(p=()=>true)=>{const i=q.findIndex(p);if(i>=0)return Promise.resolve(q.splice(i,1)[0]);return new Promise((r,j)=>{const t=setTimeout(()=>j(new Error("frame timeout")),2000);waits.push({p,r,j,t});});};}
test("authenticated protocol exposes conversation operations without model execution",async()=>{const root=await mkdtemp(join(tmpdir(),"openrill-step006-proto-"));const env={OPENRILL_DATA_ROOT:join(root,"data"),OPENRILL_CONFIG_ROOT:join(root,"config")};const host=await startLocalHost({profile:"proto",port:0,env,workspaceIds:["alpha"]});try{await host.ready;const meta=await readHostMetadata(host.paths);const ws=new WebSocket(`ws://127.0.0.1:${host.port}/protocol`,"openrill.local.v1");const next=collector(ws);await new Promise(r=>ws.addEventListener("open",r,{once:true}));ws.send(JSON.stringify({type:"open",minProtocol:1,maxProtocol:1,client:{id:"step006",version:"1",platform:process.platform,kind:"test"},credential:{kind:"profile-token",token:meta.protocolToken}}));const accepted=await next(f=>f.type==="accepted");assert.ok(accepted.capabilities.operations.some(x=>x.name==="conversation.create"));ws.send(JSON.stringify({type:"call",callId:"create",idempotencyKey:"create",operation:"conversation.create",input:{workspaceId:"alpha",title:"Protocol"}}));const created=await next(f=>f.type==="result"&&f.callId==="create");assert.equal(created.ok,true);const id=created.output.conversationId;ws.send(JSON.stringify({type:"call",callId:"send",idempotencyKey:"send",operation:"conversation.send",input:{workspaceId:"alpha",conversationId:id,submissionKey:"submission",text:"hello"}}));const sent=await next(f=>f.type==="result"&&f.callId==="send");assert.equal(sent.output.run.status,"CREATED");ws.close();}finally{await host.close();await rm(root,{recursive:true,force:true});}});
