import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { resolveProfilePaths } from "../../packages/config/dist/index.js";
import { openOpenRillStateDatabase } from "../../packages/state/dist/index.js";
import { ConversationError, ConversationService, DelegationService } from "../../packages/conversations/dist/index.js";
import { createScriptedModelAdapter } from "../../packages/model-adapter/dist/index.js";
import { executeAgentRun } from "../../packages/agent-kernel/dist/index.js";
import { ToolRegistry } from "../../packages/tool-runtime/dist/index.js";
import { registerDelegationTools } from "../../packages/tools-delegation/dist/index.js";

function ids(prefix="step014c") { let n=0; return ()=>`${prefix}-${++n}`; }
const executionBudget={maxTurns:12,maxModelCalls:12,maxToolCalls:20,maxOutputTokens:128,maxTotalTokens:2_000,maxDurationMs:60_000};
const rootBudget={...executionBudget,maxDelegationDepth:2,maxActiveChildren:2,maxTotalChildren:6};
async function fixture(name="nested") {
  const root=await mkdtemp(join(tmpdir(),`openrill-step014c-${name}-`));
  const env={OPENRILL_DATA_ROOT:join(root,"data"),OPENRILL_CONFIG_ROOT:join(root,"config")};
  const paths=resolveProfilePaths({profile:name,env});
  const state=await openOpenRillStateDatabase({profilePaths:paths});
  const createId=ids(name); let clock=1_000; const now=()=>clock;
  const conversations=new ConversationService({state,workspaceIds:["alpha"],createId,now});
  const delegations=new DelegationService({state,workspaceIds:["alpha"],createId,now});
  const conversation=conversations.create({workspaceId:"alpha",modelProfile:"default"});
  const sent=conversations.send({workspaceId:"alpha",conversationId:conversation.conversationId,submissionKey:"root",text:"root task"});
  return {root,paths,state,conversations,delegations,run:sent.run,now,setNow:(value)=>{clock=value;},cleanup:async()=>{if(state.isOpen())state.close();await rm(root,{recursive:true,force:true});}};
}
function configureRoot(f,budget=rootBudget,tools=["agent.spawn","agent.wait","echo"]) {
  return f.delegations.configureRootBudget({runId:f.run.runId,budget,scope:{workspaceIds:["alpha"],skillIds:[],toolNames:tools}});
}
function childInput(f, overrides={}) {
  return {
    parentRunId:overrides.parentRunId??f.run.runId,
    parentAttemptId:overrides.parentAttemptId??f.run.currentAttemptId,
    idempotencyKey:overrides.idempotencyKey??"child",
    task:overrides.task??"delegated task",
    workspaceId:"alpha",
    budget:overrides.budget??{maxTurns:3,maxModelCalls:3,maxToolCalls:2,maxOutputTokens:64,maxTotalTokens:300,maxDurationMs:10_000,maxDelegationDepth:2,maxActiveChildren:1,maxTotalChildren:2},
    scope:overrides.scope??{workspaceIds:["alpha"],skillIds:[],toolNames:["agent.spawn","agent.wait","echo"]},
    expectedOutput:"TEXT",
    parentToolCallId:overrides.parentToolCallId??`spawn-${overrides.idempotencyKey??"child"}`,
  };
}
function completeRun(f, runId, usage={turns:1,inputTokens:20,outputTokens:10,modelCalls:1,toolCalls:0}, text="child result") {
  const envelope=f.delegations.budget(runId);
  f.conversations.startExecution({runId,providerId:"fixture",modelId:"fixture",budget:{maxTurns:envelope.maxTurns,maxModelCalls:envelope.maxModelCalls,maxToolCalls:envelope.maxToolCalls,maxOutputTokens:envelope.maxOutputTokens,maxTotalTokens:envelope.maxTotalTokens,maxDurationMs:envelope.maxDurationMs}});
  f.conversations.appendExecutionMessage({runId,role:"assistant",content:{type:"assistant",text,reasoningSummary:null,toolCalls:[]}});
  f.conversations.completeExecution(runId,usage,"stop");
}
const resolver=(adapter)=>({resolve:()=>({profile:"default",adapter,provider:"fixture",model:"fixture",maxOutputTokens:128,maxRetries:0})});

test("migration 014 owns durable reservation release and delegated usage columns",async()=>{const f=await fixture("schema");try{assert.ok(f.state.schemaVersion>=14);assert.ok(f.state.appliedMigrations.some(m=>m.version===14&&m.name==="delegation_reservation_release_and_recovery"));const db=new DatabaseSync(f.state.diagnostics().databasePath,{readOnly:true});try{assert.equal(db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name='run_delegation_budget_reservations'").get().name,"run_delegation_budget_reservations");const columns=db.prepare("PRAGMA table_info(run_budget_envelopes)").all().map(row=>row.name);for(const name of ["delegated_used_turns","delegated_used_input_tokens","delegated_used_output_tokens","delegated_used_model_calls","delegated_used_tool_calls"])assert.ok(columns.includes(name),name);}finally{db.close();}}finally{await f.cleanup();}});

test("parallel reservations enforce active capacity and return unused budget as actual usage",async()=>{const f=await fixture("reservations");try{configureRoot(f,{...rootBudget,maxTotalTokens:1_000,maxActiveChildren:2,maxTotalChildren:3});const one=f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"one"}));const two=f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"two"}));assert.throws(()=>f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"blocked"})),e=>e instanceof ConversationError&&e.code==="DELEGATION_ACTIVE_CHILD_LIMIT");completeRun(f,one.delegation.childRunId,{turns:1,inputTokens:20,outputTokens:30,modelCalls:1,toolCalls:0});const completion=f.delegations.completeChild(one.delegation.childRunId);assert.equal(completion.result.status,"COMPLETED");const reservation=f.state.transaction(r=>r.delegations.getBudgetReservation(one.delegation.delegationId));assert.equal(reservation.status,"RELEASED");assert.equal(reservation.reservedTotalTokens,300);assert.equal(reservation.chargedInputTokens+reservation.chargedOutputTokens,50);const parent=f.delegations.budget(f.run.runId);assert.equal(parent.delegatedUsedInputTokens+parent.delegatedUsedOutputTokens,50);const three=f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"three"}));assert.equal(three.delegation.status,"CREATED");assert.notEqual(three.delegation.childRunId,two.delegation.childRunId);}finally{await f.cleanup();}});

test("agent.spawn permits bounded depth-2 nesting but rejects depth 3",async()=>{const f=await fixture("nested-tools");try{configureRoot(f);const tools=new ToolRegistry();registerDelegationTools(tools,{delegations:f.delegations,scheduleChild:()=>true,now:f.now});const rootSpawn=await tools.execute("agent.spawn",{task:"child",maxNestedDepth:1,maxActiveChildren:1,maxTotalChildren:2,toolNames:["echo"]},{runId:f.run.runId,attemptId:f.run.currentAttemptId,workspaceId:"alpha",conversationId:"root",toolCallId:"root-spawn"});assert.equal(rootSpawn.isError,false);const child=f.delegations.get(rootSpawn.output.delegationId);const childBudget=f.delegations.budget(child.childRunId);assert.equal(child.depth,1);assert.deepEqual(childBudget.allowedToolNames,["agent.spawn","agent.wait","echo"]);const childRun=f.conversations.executionContext(child.childRunId).run;const nested=await tools.execute("agent.spawn",{task:"grandchild",maxNestedDepth:0,toolNames:["echo"]},{runId:child.childRunId,attemptId:childRun.currentAttemptId,workspaceId:"alpha",conversationId:child.childConversationId,toolCallId:"child-spawn"});assert.equal(nested.isError,false);const grand=f.delegations.get(nested.output.delegationId);assert.equal(grand.depth,2);const grandRun=f.conversations.executionContext(grand.childRunId).run;const tooDeep=await tools.execute("agent.spawn",{task:"too deep",maxNestedDepth:0,toolNames:[]},{runId:grand.childRunId,attemptId:grandRun.currentAttemptId,workspaceId:"alpha",conversationId:grand.childConversationId,toolCallId:"grand-spawn"});assert.equal(tooDeep.isError,true);assert.equal(tooDeep.output.error.code,"DELEGATION_DEPTH_EXCEEDED");}finally{await f.cleanup();}});

test("Agent Kernel charges completed descendant tokens against the parent total budget",async()=>{const f=await fixture("composite-budget");try{configureRoot(f,{...rootBudget,maxTotalTokens:10,maxOutputTokens:8});const child=f.delegations.createDelegatedRun(childInput(f,{budget:{maxTurns:2,maxModelCalls:2,maxToolCalls:0,maxOutputTokens:6,maxTotalTokens:7,maxDurationMs:10_000,maxDelegationDepth:1,maxActiveChildren:0,maxTotalChildren:0},scope:{workspaceIds:["alpha"],skillIds:[],toolNames:[]}}));completeRun(f,child.delegation.childRunId,{turns:1,inputTokens:4,outputTokens:3,modelCalls:1,toolCalls:0});f.delegations.completeChild(child.delegation.childRunId);const adapter=createScriptedModelAdapter({turns:[{kind:"events",events:[{type:"usage",usage:{inputTokens:2,outputTokens:2,totalTokens:4}},{type:"completed",stopReason:"stop"}]}]});const result=await executeAgentRun({runId:f.run.runId,conversations:f.conversations,delegations:f.delegations,modelAdapters:resolver(adapter),tools:new ToolRegistry(),budget:{maxTurns:rootBudget.maxTurns,maxModelCalls:rootBudget.maxModelCalls,maxToolCalls:rootBudget.maxToolCalls,maxOutputTokens:8,maxTotalTokens:10,maxDurationMs:rootBudget.maxDurationMs}});assert.equal(result.status,"FAILED");assert.equal(result.terminalReason,"AGENT_TOTAL_TOKEN_BUDGET_EXCEEDED");assert.equal(f.delegations.budget(f.run.runId).delegatedUsedInputTokens+f.delegations.budget(f.run.runId).delegatedUsedOutputTokens,7);}finally{await f.cleanup();}});

test("cancellation cascade is deepest-first and releases each reservation exactly once",async()=>{const f=await fixture("cancel");try{configureRoot(f);const child=f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"child"}));const childContext=f.conversations.executionContext(child.delegation.childRunId);const grand=f.delegations.createDelegatedRun(childInput(f,{parentRunId:child.delegation.childRunId,parentAttemptId:childContext.run.currentAttemptId,idempotencyKey:"grand",budget:{maxTurns:1,maxModelCalls:1,maxToolCalls:0,maxOutputTokens:32,maxTotalTokens:100,maxDurationMs:5_000,maxDelegationDepth:2,maxActiveChildren:0,maxTotalChildren:0},scope:{workspaceIds:["alpha"],skillIds:[],toolNames:[]}}));assert.deepEqual(f.delegations.cancellationOrder(f.run.runId).map(row=>row.childRunId),[grand.delegation.childRunId,child.delegation.childRunId]);const completions=f.delegations.terminateDescendants(f.run.runId,"CANCELLED","PARENT_CANCELLED");assert.deepEqual(completions.map(x=>x.result.status),["CANCELLED","CANCELLED"]);assert.equal(f.delegations.get(child.delegation.delegationId).status,"CANCELLED");assert.equal(f.delegations.get(grand.delegation.delegationId).status,"CANCELLED");const first=f.delegations.budget(f.run.runId);const replay=f.delegations.terminateDescendants(f.run.runId,"CANCELLED","PARENT_CANCELLED");assert.equal(replay.length,0);const second=f.delegations.budget(f.run.runId);assert.deepEqual({t:first.delegatedUsedTurns,i:first.delegatedUsedInputTokens,o:first.delegatedUsedOutputTokens,m:first.delegatedUsedModelCalls,c:first.delegatedUsedToolCalls},{t:second.delegatedUsedTurns,i:second.delegatedUsedInputTokens,o:second.delegatedUsedOutputTokens,m:second.delegatedUsedModelCalls,c:second.delegatedUsedToolCalls});}finally{await f.cleanup();}});

test("expired child timeout produces one typed terminal delivery and clears parent wait",async()=>{const f=await fixture("timeout");try{configureRoot(f);const child=f.delegations.createDelegatedRun(childInput(f,{budget:{maxTurns:2,maxModelCalls:2,maxToolCalls:1,maxOutputTokens:64,maxTotalTokens:200,maxDurationMs:10,maxDelegationDepth:1,maxActiveChildren:0,maxTotalChildren:0},scope:{workspaceIds:["alpha"],skillIds:[],toolNames:["echo"]}}));f.delegations.markWaiting(f.run.runId,child.delegation.delegationId,{parentAttemptId:f.run.currentAttemptId,parentToolCallId:"wait-timeout",toolName:"agent.wait"});f.setNow(1_011);assert.deepEqual(f.delegations.expiredChildRunIds(),[child.delegation.childRunId]);const completion=f.delegations.terminateChild(child.delegation.childRunId,"TIMED_OUT","DELEGATION_TIMEOUT");assert.equal(completion.result.status,"TIMED_OUT");assert.equal(completion.result.errorCode,"DELEGATION_TIMEOUT");assert.equal(f.delegations.waitState(f.run.runId),null);const messages=f.conversations.executionContext(f.run.runId).messages.filter(m=>m.role==="tool"&&m.content.toolCallId==="wait-timeout");assert.equal(messages.length,1);assert.equal(messages[0].content.output.status,"TIMED_OUT");assert.equal(f.delegations.completeChild(child.delegation.childRunId).replayed,true);}finally{await f.cleanup();}});

test("restart reconciliation delivers a terminal child once and runnable recovery skips waiting children",async()=>{const f=await fixture("restart");try{configureRoot(f);const child=f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"terminal"}));f.delegations.markWaiting(f.run.runId,child.delegation.delegationId,{parentAttemptId:f.run.currentAttemptId,parentToolCallId:"wait-restart",toolName:"agent.wait"});completeRun(f,child.delegation.childRunId,{turns:1,inputTokens:1,outputTokens:1,modelCalls:1,toolCalls:0},"recovered result");f.state.close();const state2=await openOpenRillStateDatabase({profilePaths:f.paths});const conversations2=new ConversationService({state:state2,workspaceIds:["alpha"],createId:ids("restart2"),now:f.now});const delegations2=new DelegationService({state:state2,workspaceIds:["alpha"],createId:ids("restart2d"),now:f.now});const first=delegations2.reconcileTerminalChildren();const second=delegations2.reconcileTerminalChildren();assert.equal(first.length,1);assert.equal(first[0].resumeParent,true);assert.equal(second.length,0);const messages=conversations2.executionContext(f.run.runId).messages.filter(m=>m.role==="tool"&&m.content.toolCallId==="wait-restart");assert.equal(messages.length,1);const runnableParent=conversations2.create({workspaceId:"alpha",modelProfile:"default"});const sent=conversations2.send({workspaceId:"alpha",conversationId:runnableParent.conversationId,submissionKey:"other",text:"other"});delegations2.configureRootBudget({runId:sent.run.runId,budget:rootBudget,scope:{workspaceIds:["alpha"],skillIds:[],toolNames:["agent.wait"]}});const pending=delegations2.createDelegatedRun({parentRunId:sent.run.runId,parentAttemptId:sent.run.currentAttemptId,idempotencyKey:"pending",task:"pending",workspaceId:"alpha",budget:{maxTurns:2,maxModelCalls:2,maxToolCalls:1,maxOutputTokens:32,maxTotalTokens:200,maxDurationMs:1_000,maxDelegationDepth:2,maxActiveChildren:1,maxTotalChildren:1},scope:{workspaceIds:["alpha"],skillIds:[],toolNames:["agent.wait"]},expectedOutput:"TEXT"});assert.ok(delegations2.runnableChildRunIds().includes(pending.delegation.childRunId));const pendingRun=conversations2.executionContext(pending.delegation.childRunId).run;const grand=delegations2.createDelegatedRun({parentRunId:pending.delegation.childRunId,parentAttemptId:pendingRun.currentAttemptId,idempotencyKey:"nested-wait",task:"nested",workspaceId:"alpha",budget:{maxTurns:1,maxModelCalls:1,maxToolCalls:0,maxOutputTokens:16,maxTotalTokens:50,maxDurationMs:500,maxDelegationDepth:2,maxActiveChildren:0,maxTotalChildren:0},scope:{workspaceIds:["alpha"],skillIds:[],toolNames:[]},expectedOutput:"TEXT"});delegations2.markWaiting(pending.delegation.childRunId,grand.delegation.delegationId);assert.ok(!delegations2.runnableChildRunIds().includes(pending.delegation.childRunId));state2.close();}finally{await f.cleanup();}});
