import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { resolveProfilePaths } from "../../packages/config/dist/index.js";
import { openOpenRillStateDatabase } from "../../packages/state/dist/index.js";
import { ConversationError, ConversationService, DelegationService } from "../../packages/conversations/dist/index.js";
import { createScriptedModelAdapter } from "../../packages/model-adapter/dist/index.js";
import { executeAgentRun } from "../../packages/agent-kernel/dist/index.js";
import { ToolRegistry } from "../../packages/tool-runtime/dist/index.js";

function ids(prefix="step014a") { let n=0; return ()=>`${prefix}-${++n}`; }
function budget(overrides={}) { return { maxTurns:8,maxModelCalls:10,maxToolCalls:16,maxOutputTokens:128,maxTotalTokens:4096,maxDurationMs:60_000,maxDelegationDepth:2,maxActiveChildren:2,maxTotalChildren:4,...overrides }; }
function scope(overrides={}) { return { workspaceIds:["alpha"],skillIds:["research"],toolNames:["workspace.read","browser.snapshot"],...overrides }; }
async function fixture(name="delegation", now) {
  const root=await mkdtemp(join(tmpdir(),`openrill-step014a-${name}-`));
  const env={OPENRILL_DATA_ROOT:join(root,"data"),OPENRILL_CONFIG_ROOT:join(root,"config")};
  const paths=resolveProfilePaths({profile:name,env});
  const state=await openOpenRillStateDatabase({profilePaths:paths});
  const createId=ids(name);
  const conversations=new ConversationService({state,workspaceIds:["alpha"],createId,...(now?{now}: {})});
  const delegations=new DelegationService({state,workspaceIds:["alpha"],createId});
  const conversation=conversations.create({workspaceId:"alpha",modelProfile:"default"});
  const sent=conversations.send({workspaceId:"alpha",conversationId:conversation.conversationId,submissionKey:"root",text:"root task"});
  return {root,env,paths,state,conversations,delegations,run:sent.run,cleanup:async()=>{if(state.isOpen())state.close();await rm(root,{recursive:true,force:true});}};
}
function childInput(f, overrides={}) { return { parentRunId:f.run.runId,parentAttemptId:f.run.currentAttemptId,idempotencyKey:"child-1",task:"inspect the repository",workspaceId:"alpha",budget:budget({maxTurns:3,maxModelCalls:4,maxToolCalls:4,maxTotalTokens:1000,maxDurationMs:30_000,maxActiveChildren:1,maxTotalChildren:2}),scope:scope({toolNames:["workspace.read"]}),expectedOutput:"TEXT",...overrides }; }

test("migration 012 owns durable delegation graph, budget envelope, and wait projection",async()=>{const f=await fixture("schema");try{assert.ok(f.state.schemaVersion>=12);const names=f.state.appliedMigrations.map(x=>x.name);assert.ok(names.includes("delegation_graph_budget_foundation"));const db=new DatabaseSync(f.state.diagnostics().databasePath,{readOnly:true});try{for(const table of ["run_budget_envelopes","run_delegations","run_delegation_events","run_delegation_waits"]){const row=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name=?").get(table);assert.equal(row?.name,table);}}finally{db.close();}const sql=await readFile(new URL("../../packages/state/migrations/012_delegation_graph_budget_foundation.sql",import.meta.url),"utf8");assert.ok(sql.includes("state TEXT NOT NULL CHECK (state = 'WAITING_DELEGATION')"));assert.equal(sql.includes("used_input_tokens + used_output_tokens <= max_total_tokens"),false);}finally{await f.cleanup();}});

test("root budget configuration is replay-safe and rejects mutable identity drift",async()=>{const f=await fixture("root-budget");try{const first=f.delegations.configureRootBudget({runId:f.run.runId,budget:budget(),scope:scope()});const second=f.delegations.configureRootBudget({runId:f.run.runId,budget:budget(),scope:scope()});assert.deepEqual(second,first);assert.throws(()=>f.delegations.configureRootBudget({runId:f.run.runId,budget:budget({maxTotalTokens:5000}),scope:scope()}),e=>e instanceof ConversationError&&e.code==="DELEGATION_BUDGET_CONFLICT");}finally{await f.cleanup();}});

test("child creation is atomic, task text stays in child transcript, and delegation stores only SHA-256",async()=>{const f=await fixture("child");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget(),scope:scope()});const out=f.delegations.createDelegatedRun(childInput(f));assert.equal(out.replayed,false);assert.equal(out.delegation.parentRunId,f.run.runId);assert.equal(out.delegation.depth,1);assert.equal(out.delegation.taskSha256,createHash("sha256").update("inspect the repository").digest("hex"));const child=f.conversations.executionContext(out.delegation.childRunId);assert.equal(child.messages[0].content.text,"inspect the repository");const raw=f.state.transaction(r=>r.delegations.getDelegation(out.delegation.delegationId));assert.equal(JSON.stringify(raw).includes("inspect the repository"),false);assert.deepEqual(out.childBudget.allowedToolNames,["workspace.read"]);}finally{await f.cleanup();}});

test("delegation idempotency replays exact input and rejects conflicting input",async()=>{const f=await fixture("idempotency");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget(),scope:scope()});const first=f.delegations.createDelegatedRun(childInput(f));const replay=f.delegations.createDelegatedRun(childInput(f));assert.equal(replay.replayed,true);assert.equal(replay.delegation.childRunId,first.delegation.childRunId);assert.throws(()=>f.delegations.createDelegatedRun(childInput(f,{task:"different"})),e=>e instanceof ConversationError&&e.code==="DELEGATION_IDEMPOTENCY_CONFLICT");}finally{await f.cleanup();}});

test("workspace, skill, and Tool scopes cannot widen",async()=>{const f=await fixture("scope");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget(),scope:scope()});assert.throws(()=>f.delegations.createDelegatedRun(childInput(f,{scope:scope({toolNames:["workspace.read","process.run"]})})),e=>e instanceof ConversationError&&e.code==="DELEGATION_SCOPE_ESCALATION");assert.throws(()=>f.delegations.createDelegatedRun(childInput(f,{scope:scope({skillIds:["research","admin"]})})),e=>e instanceof ConversationError&&e.code==="DELEGATION_SCOPE_ESCALATION");}finally{await f.cleanup();}});

test("depth, active child, total child, and remaining budget limits fail closed",async()=>{const f=await fixture("limits");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget({maxActiveChildren:1,maxTotalChildren:2,maxTurns:5,maxModelCalls:6,maxToolCalls:6,maxTotalTokens:1500}),scope:scope()});const first=f.delegations.createDelegatedRun(childInput(f,{budget:budget({maxTurns:3,maxModelCalls:4,maxToolCalls:4,maxTotalTokens:1000,maxDurationMs:30_000,maxActiveChildren:1,maxTotalChildren:2})}));assert.throws(()=>f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"child-2"})),e=>e instanceof ConversationError&&e.code==="DELEGATION_ACTIVE_CHILD_LIMIT");const childFixture={...f,run:{runId:first.delegation.childRunId,currentAttemptId:f.conversations.executionContext(first.delegation.childRunId).run.currentAttemptId}};const grand=f.delegations.createDelegatedRun(childInput(childFixture,{idempotencyKey:"grand",budget:budget({maxTurns:1,maxModelCalls:1,maxToolCalls:0,maxOutputTokens:50,maxTotalTokens:100,maxDurationMs:10_000,maxDelegationDepth:2,maxActiveChildren:0,maxTotalChildren:0}),scope:scope({toolNames:[]})}));assert.equal(grand.delegation.depth,2);const grandFixture={...f,run:{runId:grand.delegation.childRunId,currentAttemptId:f.conversations.executionContext(grand.delegation.childRunId).run.currentAttemptId}};assert.throws(()=>f.delegations.createDelegatedRun(childInput(grandFixture,{idempotencyKey:"too-deep",budget:budget({maxTurns:1,maxModelCalls:1,maxToolCalls:0,maxOutputTokens:25,maxTotalTokens:50,maxDurationMs:5_000,maxDelegationDepth:2,maxActiveChildren:0,maxTotalChildren:0}),scope:scope({toolNames:[]})})),e=>e instanceof ConversationError&&e.code==="DELEGATION_DEPTH_EXCEEDED");}finally{await f.cleanup();}});

test("durable WAITING_DELEGATION survives reopen and makes restart classification resumable",async()=>{const f=await fixture("wait");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget(),scope:scope()});const child=f.delegations.createDelegatedRun(childInput(f));f.conversations.transitionRun({runId:f.run.runId,status:"RUNNING"});const wait=f.delegations.markWaiting(f.run.runId,child.delegation.delegationId);assert.equal(wait.state,"WAITING_DELEGATION");f.state.close();const state2=await openOpenRillStateDatabase({profilePaths:f.paths});const conversations2=new ConversationService({state:state2,workspaceIds:["alpha"]});const delegations2=new DelegationService({state:state2,workspaceIds:["alpha"]});const [classification]=conversations2.recoverIncompleteRuns();assert.equal(classification.status,"CREATED");assert.equal(classification.recoveryState,"RESUMABLE");assert.equal(delegations2.waitState(f.run.runId).state,"WAITING_DELEGATION");state2.close();}finally{await f.cleanup();}});

test("Agent Kernel enforces cumulative total-token budget and persists aggregate usage",async()=>{const f=await fixture("tokens");try{const adapter=createScriptedModelAdapter({turns:[{kind:"events",events:[{type:"usage",usage:{inputTokens:4,outputTokens:3,totalTokens:7}},{type:"completed",stopReason:"stop"}]}]});const resolver={resolve:async()=>({profile:"default",adapter,provider:"fixture",model:"fixture",maxOutputTokens:5,maxRetries:0})};const out=await executeAgentRun({runId:f.run.runId,conversations:f.conversations,modelAdapters:resolver,tools:new ToolRegistry(),budget:{maxOutputTokens:5,maxTotalTokens:6,maxDurationMs:1000}});assert.equal(out.status,"FAILED");assert.equal(out.terminalReason,"AGENT_TOTAL_TOKEN_BUDGET_EXCEEDED");assert.equal(out.usage.inputTokens+out.usage.outputTokens,7);assert.equal(f.delegations.budget(f.run.runId).usedInputTokens,4);}finally{await f.cleanup();}});

test("Agent Kernel enforces a durable wall-clock deadline",async()=>{const f=await fixture("time");try{const adapter={id:"slow",async *stream(){await new Promise(r=>setTimeout(r,10));yield {type:"completed",stopReason:"stop"};}};const resolver={resolve:async()=>({profile:"default",adapter,provider:"fixture",model:"fixture",maxOutputTokens:1,maxRetries:0})};const out=await executeAgentRun({runId:f.run.runId,conversations:f.conversations,modelAdapters:resolver,tools:new ToolRegistry(),budget:{maxOutputTokens:1,maxTotalTokens:10,maxDurationMs:1}});assert.equal(out.status,"FAILED");assert.equal(out.terminalReason,"AGENT_TIME_BUDGET_EXCEEDED");}finally{await f.cleanup();}});


test("observed usage may exceed a configured ceiling so typed budget failure evidence remains durable",async()=>{const f=await fixture("overshoot-evidence");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget({maxOutputTokens:5,maxTotalTokens:6}),scope:scope()});f.conversations.updateExecutionUsage(f.run.runId,{turns:1,inputTokens:4,outputTokens:3,modelCalls:1,toolCalls:0},"AGENT_TOTAL_TOKEN_BUDGET_EXCEEDED");const envelope=f.delegations.budget(f.run.runId);assert.equal(envelope.usedInputTokens+envelope.usedOutputTokens,7);assert.equal(envelope.maxTotalTokens,6);const attempt=f.conversations.executionContext(f.run.runId).attempt;assert.equal(attempt.terminalReason,"AGENT_TOTAL_TOKEN_BUDGET_EXCEEDED");}finally{await f.cleanup();}});

test("turn usage aggregates by SUM across restart attempts instead of MAX",async()=>{const f=await fixture("turn-sum");try{const now=Date.now();f.state.transaction(r=>{r.conversations.updateAttemptUsage({attemptId:f.run.currentAttemptId,turns:1,inputTokens:1,outputTokens:1,modelCalls:1,toolCalls:0,updatedAt:now});const second="turn-sum-attempt-2";r.conversations.insertAttempt({attemptId:second,runId:f.run.runId,attemptNumber:2,status:"RUNNING",startedAt:now,endedAt:null,recoveryReason:"HOST_RESTART",providerId:null,modelId:null,maxTurns:null,maxModelCalls:null,maxToolCalls:null,maxOutputTokens:null,maxTotalTokens:null,maxDurationMs:null,usedTurns:0,usedInputTokens:0,usedOutputTokens:0,modelCallCount:0,toolCallCount:0,terminalReason:null,createdAt:now,updatedAt:now});r.conversations.updateAttemptUsage({attemptId:second,turns:1,inputTokens:2,outputTokens:2,modelCalls:1,toolCalls:0,updatedAt:now});const total=r.conversations.aggregateRunUsage(f.run.runId);assert.deepEqual(total,{turns:2,inputTokens:3,outputTokens:3,modelCalls:2,toolCalls:0});});}finally{await f.cleanup();}});

test("total-child and remaining-capacity limits are independent from active-child limits",async()=>{const f=await fixture("independent-limits");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget({maxActiveChildren:2,maxTotalChildren:2,maxTurns:6,maxModelCalls:6,maxToolCalls:6,maxTotalTokens:1500}),scope:scope()});const one=f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"one",budget:budget({maxTurns:2,maxModelCalls:2,maxToolCalls:2,maxOutputTokens:100,maxTotalTokens:1000,maxDurationMs:20_000,maxActiveChildren:0,maxTotalChildren:0})}));assert.throws(()=>f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"too-large",budget:budget({maxTurns:2,maxModelCalls:2,maxToolCalls:2,maxOutputTokens:100,maxTotalTokens:600,maxDurationMs:20_000,maxActiveChildren:0,maxTotalChildren:0})})),e=>e instanceof ConversationError&&e.code==="DELEGATION_BUDGET_EXCEEDED");f.delegations.transitionDelegation({delegationId:one.delegation.delegationId,status:"RUNNING"});f.delegations.transitionDelegation({delegationId:one.delegation.delegationId,status:"COMPLETED",resultSummary:{ok:true}});const two=f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"two",budget:budget({maxTurns:2,maxModelCalls:2,maxToolCalls:2,maxOutputTokens:100,maxTotalTokens:500,maxDurationMs:20_000,maxActiveChildren:0,maxTotalChildren:0})}));f.delegations.transitionDelegation({delegationId:two.delegation.delegationId,status:"RUNNING"});f.delegations.transitionDelegation({delegationId:two.delegation.delegationId,status:"COMPLETED"});assert.throws(()=>f.delegations.createDelegatedRun(childInput(f,{idempotencyKey:"three",budget:budget({maxTurns:1,maxModelCalls:1,maxToolCalls:0,maxOutputTokens:50,maxTotalTokens:100,maxDurationMs:10_000,maxActiveChildren:0,maxTotalChildren:0}),scope:scope({toolNames:[]})})),e=>e instanceof ConversationError&&e.code==="DELEGATION_TOTAL_CHILD_LIMIT");}finally{await f.cleanup();}});


test("delegation transitions are append-only, terminal transitions clear waits, and cancellation order is deepest-first",async()=>{const f=await fixture("transitions");try{f.delegations.configureRootBudget({runId:f.run.runId,budget:budget({maxActiveChildren:2,maxTotalChildren:4}),scope:scope()});const child=f.delegations.createDelegatedRun(childInput(f,{budget:budget({maxTurns:3,maxModelCalls:3,maxToolCalls:3,maxOutputTokens:100,maxTotalTokens:1000,maxDurationMs:30_000,maxDelegationDepth:2,maxActiveChildren:1,maxTotalChildren:2})}));f.delegations.transitionDelegation({delegationId:child.delegation.delegationId,status:"RUNNING"});f.delegations.markWaiting(f.run.runId,child.delegation.delegationId);const childContext=f.conversations.executionContext(child.delegation.childRunId);const grand=f.delegations.createDelegatedRun({parentRunId:child.delegation.childRunId,parentAttemptId:childContext.run.currentAttemptId,idempotencyKey:"grandchild",task:"nested task",workspaceId:"alpha",budget:budget({maxTurns:1,maxModelCalls:1,maxToolCalls:0,maxOutputTokens:50,maxTotalTokens:100,maxDurationMs:10_000,maxDelegationDepth:2,maxActiveChildren:0,maxTotalChildren:0}),scope:scope({toolNames:[]}),expectedOutput:"TEXT"});assert.deepEqual(f.delegations.cancellationOrder(f.run.runId).map(x=>x.delegationId),[grand.delegation.delegationId,child.delegation.delegationId]);const completed=f.delegations.transitionDelegation({delegationId:child.delegation.delegationId,status:"COMPLETED",resultSummary:"bounded result"});assert.equal(completed.resultSummarySha256?.length,64);assert.equal(f.delegations.waitState(f.run.runId),null);assert.throws(()=>f.delegations.transitionDelegation({delegationId:child.delegation.delegationId,status:"RUNNING"}),e=>e instanceof ConversationError&&e.code==="RUN_STATE_INVALID");assert.deepEqual(f.delegations.events(child.delegation.delegationId).map(e=>e.eventType),["CREATED","STARTED","WAITING","COMPLETED"]);}finally{await f.cleanup();}});


test("legacy execution budget callers receive durable total-token and duration defaults",async()=>{const f=await fixture("legacy-budget");try{const started=f.conversations.startExecution({runId:f.run.runId,providerId:"fixture",modelId:"fixture",budget:{maxTurns:4,maxModelCalls:4,maxToolCalls:4,maxOutputTokens:128}});assert.equal(started.attempt.maxTotalTokens,65_536);assert.equal(started.attempt.maxDurationMs,15*60*1000);assert.equal(started.budgetEnvelope.maxTotalTokens,65_536);assert.equal(started.budgetEnvelope.maxDurationMs,15*60*1000);}finally{await f.cleanup();}});

test("Kernel deadline checks use the Conversation durable clock domain",async()=>{let now=100;const f=await fixture("shared-clock",()=>now);try{const adapter=createScriptedModelAdapter({turns:[{kind:"events",events:[{type:"completed",stopReason:"stop"}]}]});const out=await executeAgentRun({runId:f.run.runId,conversations:f.conversations,modelAdapters:{resolve:()=>({profile:"default",adapter,provider:"fixture",model:"fixture",maxOutputTokens:8,maxRetries:0})},tools:new ToolRegistry(),budget:{maxOutputTokens:8,maxTotalTokens:32,maxDurationMs:10}});assert.equal(out.status,"COMPLETED");now=111;assert.equal(f.conversations.currentTime(),111);}finally{await f.cleanup();}});
