import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=path=>readFile(new URL(`../../${path}`,import.meta.url),"utf8");

test("historical STEP014DR7 identity remains documented without freezing the current release",async()=>{const pkg=JSON.parse(await read("package.json"));const accepted=JSON.parse(await read("config/current-accepted-baseline.json"));assert.equal(pkg.scripts["acceptance:step014dr7"],"python scripts/run_step014dr7_acceptance.py");assert.equal(pkg.scripts["package:step014dr7"],"python scripts/package_step014dr7.py --output ../openrill-step014dr7-live-acceptance-transport-lifecycle-closure-audit-v1.zip");assert.ok((await read("docs/plans/STEP014DR7_LIVE_ACCEPTANCE_TRANSPORT_AND_LIFECYCLE_CLOSURE_AUDIT.md")).includes("0.14.10-step014dr7"));assert.notEqual(pkg.version,"0.14.10-step014dr7");assert.equal(typeof accepted.step,"string");assert.ok(accepted.step.length>0);});

test("STEP014DR7 is acceptance-only and retains schema Tool Protocol and UI surfaces",async()=>{const migrations=await read("packages/state/src/migrations.ts");const tools=await read("packages/tools-delegation/src/index.ts");const registry=await read("services/agent-host/src/transport/operation-registry.ts");const ui=await read("apps/agent-web/src/browser-app.ts");assert.match(migrations,/OPENRILL_STATE_SCHEMA_VERSION = (?:1[4-9]|[2-9]\d+) as const/);for(const name of ["agent.spawn","agent.wait"])assert.ok(tools.includes(name));for(const name of ["delegation.list","delegation.get","delegation.cancel"])assert.ok(registry.includes(name));assert.ok(ui.includes("\"delegations\""));assert.ok(ui.includes("\"data-testid\": `nav-${item}`"));});

test("STEP014DR7 documents the closure audit and both recurrence issues",async()=>{for(const id of ["OR-ISSUE-176","OR-ISSUE-177","OR-ISSUE-178","OR-ISSUE-179","OR-ISSUE-180","OR-ISSUE-181","OR-ISSUE-182","OR-ISSUE-183"]){assert.ok((await read("docs/governance/ENGINEERING_ISSUE_REGISTRY.md")).includes(id));assert.ok((await read("docs/testing/RECURRENCE_PREVENTION_GATES.md")).includes(id));assert.ok((await read(`reference/validation/STEP014DR7_${id.replaceAll("-","_")}.md`)).includes(id));}assert.ok((await read("reference/validation/STEP014_ACCEPTANCE_CLOSURE_AUDIT.md")).includes("live-loopback-http.mjs"));});

test("STEP014DR7 acceptance runs lifecycle audit before both live stages",async()=>{const source=await read("scripts/run_step014dr7_acceptance.py");const audit=source.indexOf('"live-acceptance-lifecycle-audit"');const external=source.indexOf('"external-model-parallel-live"');const nested=source.indexOf('"deterministic-nested-control-ui-live"');assert.ok(audit>=0&&external>audit&&nested>external);assert.ok(source.includes("run-step014dr7-external-model-live.mjs"));assert.ok(source.includes("run-step014dr7-deterministic-nested-ui-live.mjs"));const batches=await read("scripts/run-canonical-unit-batches.mjs");assert.ok(batches.includes("async function runFile"));assert.ok(batches.includes("OPENRILL_CANONICAL_FILE_START"));assert.ok(batches.includes("OPENRILL_CANONICAL_FILE_END"));assert.ok(batches.includes('["--test", "--test-concurrency=1", "--test-reporter=tap", file]'));const externalLive=await read("scripts/run-step014dr7-external-model-live.mjs");const nestedLive=await read("scripts/run-step014dr7-deterministic-nested-ui-live.mjs");for(const body of [externalLive,nestedLive]){assert.ok(body.includes('clientVersion:"0.14.10-step014dr7"'));assert.equal(body.includes("0.14.9-step014dr7"),false);}assert.ok(nestedLive.includes('./step014dr6-deterministic-nested-fixture.mjs'));assert.equal(nestedLive.includes('./step014dr7-deterministic-nested-fixture.mjs'),false);});
