import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=async(path)=>await readFile(new URL(`../../${path}`,import.meta.url),"utf8");
const STEP="STEP021BR1_PLAN_REVISION_STABLE_STEP_IDENTITY_AND_OPEN_BLOCKER_GUARD_CLOSURE";const VERSION="0.21.2-step021br1";const BASELINE="STEP021A_DURABLE_GOAL_PLAN_TO_TASK_FLOW_EXECUTOR_FOUNDATION";const LIVE="STEP021BR1_H1_CHANGED_STEP_REEXECUTION_MUTABLE_ISOLATION_OPEN_BLOCKER_AND_RESTART";

test("STEP021BR1 historical corrective identity remains retained while STEP021A stays official Product baseline",async()=>{const contract=JSON.parse(await read("config/step021br1-live-marker-contract.json"));const baseline=JSON.parse(await read("config/current-accepted-baseline.json"));assert.equal(contract.version,VERSION);assert.equal(contract.step,STEP);assert.equal(typeof baseline.step,"string");assert.ok(baseline.stateSchema>=24);assert.match(baseline.checks,/^\d+\/\d+$/);});

test("STEP021BR1 stable Step identity compares every semantic execution field",async()=>{const body=await read("packages/goal-executor/src/service.ts");assert.match(body,/function sameStableStepDefinition/);for(const token of ["stepId","title","required","retryMode","maxAttempts"])assert.match(body,new RegExp(`left\.${token} === right\.${token}`));assert.match(body,/const stable = .*sameStableStepDefinition/);});

test("STEP021BR1 resets changed Plan projection and isolates older pinned execution completion",async()=>{const body=await read("packages/goal-executor/src/service.ts");assert.match(body,/#canProjectMutablePlanStep/);assert.match(body,/!previous \|\| !sameStableStepDefinition\(previous, draft\)/);assert.match(body,/status: "PENDING"/);assert.match(body,/attemptCount: stable \? previous\.attemptCount : 0/);});

test("STEP021BR1 adoption uses an unbounded dedicated open-blocker existence query",async()=>{const body=await read("packages/goal-executor/src/service.ts");const repo=await read("packages/state/src/goal-repository.ts");const adoption=body.slice(body.indexOf("public adoptPlanRevision"),body.indexOf("public retry",body.indexOf("public adoptPlanRevision")));assert.match(adoption,/getAnyOpenBlocker/);assert.doesNotMatch(adoption,/listBlockers/);assert.match(repo,/public getAnyOpenBlocker/);assert.match(repo,/status = 'OPEN'/);});

test("STEP021BR1 Product tests cover changed completion, mutable isolation, and blocker row 201",async()=>{const body=await read("tests/unit/goal-plan-revision-retry-step021b.test.mjs");assert.match(body,/changed completed Step is reset/);assert.match(body,/pinned completion cannot contaminate the current Plan/);assert.match(body,/open blocker beyond the first 200 historical ledger rows/);assert.match(body,/for \(let index = 1; index <= 201/);});

test("STEP021BR1 Host and protocol rerun the changed Step without duplicate admission",async()=>{const host=await read("tests/unit/goal-plan-revision-host-step021b.test.mjs");const protocol=await read("tests/unit/goal-plan-revision-retry-protocol-step021b.test.mjs");assert.match(host,/Host restart reruns a changed completed Step/);assert.match(host,/length, 4/);assert.match(host,/new Set\(completed\.flow\.tasks\.map/);assert.match(protocol,/changed-Step adoption/);assert.match(protocol,/length, 5/);});

test("STEP021BR1 independently records every audit finding and recurrence gate",async()=>{const registry=await read("docs/governance/ENGINEERING_ISSUE_REGISTRY.md");const gates=await read("docs/testing/RECURRENCE_PREVENTION_GATES.md");const audit=await read("reference/validation/STEP021B_PRE_WINDOWS_LIVE_CODE_AUDIT.md");assert.match(audit,/BLOCKED_CORRECTIVE_REQUIRED/);for(let issue=303;issue<=305;issue+=1){const token=`OR-ISSUE-${issue}`;assert.match(registry,new RegExp(token));assert.match(gates,new RegExp(token));assert.match(await read(`reference/validation/STEP021BR1_OR_ISSUE_${issue}.md`),new RegExp(token));}});

test("STEP021BR1 root continuation and package entrypoints are self-contained",async()=>{for(const file of ["README.md","HANDOFF.md","PLANS.md","ROADMAP.md","VALIDATION.md","PROJECT.md","ARCHITECTURE.md"]){const body=await read(file);assert.match(body,new RegExp(STEP));assert.match(body,/0\.21\.2-step021br1/);assert.match(body,new RegExp(BASELINE));assert.match(body,/OR-ISSUE-303/);assert.match(body,/OR-ISSUE-305/);}const scripts=JSON.parse(await read("package.json")).scripts;assert.equal(scripts["acceptance:step021br1"],"python scripts/run_step021br1_acceptance.py");assert.equal(scripts["acceptance:step021br1:live"],"python scripts/run_step021br1_acceptance.py --require-windows-plan-revision-corrective-live");assert.equal(scripts["plan-revision-corrective-live:step021br1"],"node scripts/run-step021br1-plan-revision-corrective-live.mjs");assert.equal(scripts["package:step021br1"],"python scripts/package_step021br1.py --output ../openrill-step021br1-plan-revision-stable-step-identity-open-blocker-guard-closure-v1.zip");});

test("STEP021BR1 has one structured 24-check Windows live contract",async()=>{const contract=JSON.parse(await read("config/step021br1-live-marker-contract.json"));assert.equal(contract.step,STEP);assert.equal(contract.version,VERSION);assert.equal(contract.schema,24);assert.equal(contract.expectedChecks,"24/24");assert.equal(contract.liveHarness,LIVE);assert.equal(contract.fields.stability,"SEMANTIC_DEFINITION_MATCH");assert.equal(contract.fields.blocker_guard,"UNBOUNDED_OPEN_EXISTENCE");});
